name: add_to_wallet
description: Flutter plugin exposing native PKAddPassButton to interact with the Apple Wallet
version: 0.0.2
homepage: https://github.com/barkibu/add_to_wallet
repository: https://github.com/barkibu/add_to_wallet

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      # android:
      #   package: com.barkibu.add_to_wallet
      #   pluginClass: AddToWalletPlugin
      ios:
        pluginClass: AddToWalletPlugin
