name: add_to_wallet
description: Flutter plugin exposing native PKAddPassButton to interact with the Apple Wallet
version: 0.0.2
homepage: https://github.com/barkibu/add_to_wallet
repository: https://github.com/barkibu/add_to_wallet

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.4"

dependencies:
  flutter:
    sdk: flutter
  uuid: ">=3.0.7 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AddToWalletPlugin
